language: java
dist: trusty
jdk:
  - openjdk7
  - oraclejdk8

install: mvn install -DskipTests=true -B -V
script: mvn test
after_success:
 - chmod +x .travis_after_success.sh
 - ./.travis_after_success.sh

branches:
  only: master