language: java
dist: trusty
jdk:
  - openjdk7
  - oraclejdk8

install: mvn install -DskipTests=true -B -V
script: mvn test
after_success:
 - chmod 755 .travis_after_success.sh
 - ls -lrt
 - echo $TRAVIS_JDK_VERSION
 - ./.travis_after_success.sh

branches:
  only: master